/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *   mmi_rp_app_mspace_def.h
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *   Resource populate function generated by XML resgen
 *
 * Author:
 * -------
 *   MTK resgenerator XML parser
 *
 *******************************************************************************/


#ifndef _MMI_RP_APP_MSPACE_DEF_H
#define _MMI_RP_APP_MSPACE_DEF_H




/******************** Menu resource IDs - begin ********************/
typedef enum
{
    MENU_ID_MSPACE_ENTRY = 37926 + 1, /* BASE_ID + 1 */
    MENU_ID_MSPACE_OPTION_TO_UPDATE_DETAILS,
    MENU_ID_MSPACE_OPTION_TO_INSTALL_DETAILS,
    MENU_ID_MSPACE_OPTION_TO_DETAILS_DETAILS,
    MENU_ID_MSPACE_OPTION_TO_UPDATE_UPDATE,
    MENU_ID_MSPACE_OPTION_TO_INSTALL_INSTALL,
    MENU_ID_MSPACE_OPTIONS_TO_UPDATE,
    MENU_ID_MSPACE_OPTIONS_TO_INSTALL,
    MENU_ID_MSPACE_OPTIONS_TO_DETAILS,
    MMI_RP_APP_MSPACE_MENU_MAX
}mmi_rp_app_mspace_menu_enum;
/******************** Menu resource IDs - finish ********************/


/******************** String resource IDs - begin ********************/
typedef enum
{
    STR_ID_MSPACE_NAME = 37926 + 1, /* BASE_ID + 1 */
    STR_ID_MSPACE_TITLE,
    STR_ID_MSPACE_INSTALL,
    STR_ID_MSPACE_UPDATE,
    STR_ID_MSPACE_UPDATING,
    STR_ID_MSPACE_CONNECT_SERVER_FAILED,
    STR_ID_MSPACE_NO_APP,
    STR_ID_MSPACE_RETRY,
    STR_ID_MSPACE_DOWNLOADING,
    STR_ID_MSPACE_DOWNLOAD_SUCCESS,
    STR_ID_MSPACE_DOWNLOAD_FAIL,
    STR_ID_MSPACE_INSTALLING,
    STR_ID_MSPACE_INSTALL_SUCCESS,
    STR_ID_MSPACE_INSTALL_FAIL,
    STR_ID_MSPACE_APP_TIME,
    STR_ID_MSPACE_APP_SIZE,
    STR_ID_MSPACE_APP_PROVIDER,
    STR_ID_MSPACE_APP_INTRODUCTION,
    STR_ID_MSPACE_CONNECTION_FAILED,
    STR_ID_MSPACE_WAITING,
    STR_ID_VAPP_M_SPACE_MEMORY_LIMITATION,
    MMI_RP_APP_MSPACE_STR_MAX
}mmi_rp_app_mspace_str_enum;
/******************** String resource IDs - finish ********************/


/******************** Screen resource IDs - begin ********************/
typedef enum
{
    GRP_ID_MSPACE = 37926 + 1, /* BASE_ID + 1 */
    SCR_ID_MSPACE_MAIN,
    SCR_ID_MSPACE_APP_MAIN,
    SCR_ID_MSPACE_APP_INSTALL,
    SCR_ID_MSPACE_APP_UPDATE,
    SCR_ID_MSPACE_WAITING,
    SCR_ID_MSPACE_DOWNLOADING,
    MMI_RP_APP_MSPACE_SCR_MAX
}mmi_rp_app_mspace_scr_enum;
/******************** Screen resource IDs - finish ********************/
/******************** Template resource IDs - Begin ********************/
/******************** Template resource IDs - End ********************/

/******************** Venus XML resource IDs - Begin ********************/
typedef enum 
{

    MMI_RP_APP_MSPACE_VXML_LAYOUT_MAX
} mmi_rp_app_mspace_vxml_layout_enum;
/******************** Venus XML resource IDs - End ********************/



/******************** Image resource IDs - begin ********************/
typedef enum
{
    IMG_ID_MSPACE_MAIN_MENU_ICON = 37926 + 1, /* BASE_ID + 1 */
    IMG_ID_MSPACE_SUB_MENU_ICON,
    IMG_ID_MSPACE_APP_DEFAULT_ICON,
    IMG_ID_MSPACE_APP_STATUS_DEFAULT_ICON,
    IMG_ID_MSPACE_APP_STATUS_INSTALLED_ICON,
    IMG_ID_MSPACE_APP_STATUS_UPDATE_ICON,
    MMI_RP_APP_MSPACE_IMG_MAX
}mmi_rp_app_mspace_img_enum;
/******************** Image resource IDs - finish ********************/


#endif /* _MMI_RP_APP_MSPACE_DEF_H */
