/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *   mmi_rp_native_app_package_data.c
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *   Resource populate function generated by XML resgen
 *
 * Author:
 * -------
 *   MTK resgenerator XML parser
 *
 *******************************************************************************/


#include "MMIDataType.h"
#include "mmi_rp_native_app_package_data.h"
#include "mmi_rp_all_defs.h"
#include "GlobalResDef.h"

const srv_nativeappfactory_package_struct native_app_package_table[] = {
    {"native.mtk.imageviewer", NULL, (mmi_app_launch_func)mmi_imgview_launch, APP_IMAGEVIEWER, STR_ID_IMGVIEW_NAME, IMG_ID_IMGVIEW_VUI_MAIN_MENU_APP_ICON, (MMI_BOOL)0},
    {"native.mtk.sndrec", NULL, (mmi_app_launch_func)mmi_sndrec_launch_function, APP_SOUNDRECORDER, STR_ID_SNDREC_MAIN, IMG_ID_SNDREC_VUI_MAIN_MENU_APP_ICON, (MMI_BOOL)0},
    {"native.mtk.calllog", mmi_clog_appmgr_package_proc, (mmi_app_launch_func)mmi_clog_appmgr_launch, APP_CALLLOG, STR_ID_CLOG_CALL_LOG, IMG_ID_CLOG_APPMGR_MAIN_ICON, (MMI_BOOL)0},
    {"native.mtk.mspace", NULL, (mmi_app_launch_func)mmi_mspace_start, APP_MSPACE, STR_ID_MSPACE_NAME, IMG_ID_MSPACE_MAIN_MENU_ICON, (MMI_BOOL)0},
    {"native.mtk.profile", NULL, (mmi_app_launch_func)mmi_profiles_launch_function, APP_PROFILES, STR_ID_PROF_CAPTION, MAIN_MENU_USER_PROFILES_ICON, (MMI_BOOL)0},
    {"native.mtk.filemgr", NULL, (mmi_app_launch_func)mmi_fmgr_app_mgr_launch, APP_FILEMANAGER, STR_FMGR_TITLE, IMG_ID_FMGR_MAIN_MENUICON, (MMI_BOOL)0},
    {"native.mtk.setting", NULL, (mmi_app_launch_func)EntryScrSettingMenu, APP_SETTING_NEW, MAIN_MENU_SETTINGS_TEXT, MAIN_MENU_SETTINGS_IMAGE_NEW, (MMI_BOOL)0},
    {"native.mtk.services_sat", NULL, (mmi_app_launch_func)mmi_service_sat_proc, APP_SERVICES_SAT, STR_ID_SAT_MENU_TITLE, IMG_ID_SERVICE_SAT_TITLE, (MMI_BOOL)0},
    {"native.mtk.calculator", NULL, (mmi_app_launch_func)CalcPreEntryApp, APP_CALCULATOR, STR_ID_CALC_MENU, MAIN_MENU_CALC_ICON, (MMI_BOOL)0},
    {"native.mtk.alarm", NULL, (mmi_app_launch_func)EntryAlmMenu, APP_ALARM, STR_GLOBAL_ALARM, MAIN_MENU_ALARM_ICON, (MMI_BOOL)0},
    {"native.mtk.calendar", NULL, (mmi_app_launch_func)ClndrPreEntryApp, APP_CALENDAR, ORGANIZER_MENU_CALENDER_STRINGID, MAIN_MENU_CALENDAR_ICON, (MMI_BOOL)0},
    {"native.mtk.dialer", NULL, (mmi_app_launch_func)mmi_dialer_launch, APP_DIALER, STR_ID_DIALER_MENU, IMG_DIAL_ICON_FOR_COSMOS_ID, (MMI_BOOL)0},
    {"native.mtk.messaging", mmi_um_package_proc, (mmi_app_launch_func)mmi_um_entry_main_message_menu, APP_UNIFIEDMESSAGE, STR_ID_UM_MAIN_MENU_MESSAGES_TEXT, IMG_UM_LAUNCHER_ICON, (MMI_BOOL)0},
    {"native.mtk.phonebook", NULL, (mmi_app_launch_func)mmi_phb_pre_entry_main_screen, APP_PHONEBOOK, STR_SCR_PBOOK_CAPTION, IMG_ID_PHB_APP_LAUNCH, (MMI_BOOL)0},
    {"native.mtk.connectivity", NULL, (mmi_app_launch_func)mmi_connectivity_app_launch_func, APP_CONNECTIVITY_MAINMENU, STR_ID_CONNECTIVITY_TEXT, IMG_ID_CONNECTIVITY_ICON, (MMI_BOOL)0},
};

U32 srv_nativeappfactory_get_table_size(void)
{
    return sizeof(native_app_package_table)/sizeof(srv_nativeappfactory_package_struct);
}
