/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *   mmi_cache_table.c
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *   Resource populate function generated by XML resgen
 *
 * Author:
 * -------
 *   03 13 2011 yan.liang
 *
 *******************************************************************************/
/********************************************************
 *  This file is generated automatically by resource gen
 *  Please do not modify it here manually 
 ***********************************************************/
#include "common_nvram_editor_data_item.h"
#define MMI_CACHE_BYTE_NUMBER 85
#define MMI_CACHE_SHORT_NUMBER 26
#define MMI_CACHE_DOUBLE_NUMBER 33


kal_uint16 mmi_rp_mmi_cache_get_byte_number(void)
{
    return MMI_CACHE_BYTE_NUMBER;
}
kal_uint16 mmi_rp_mmi_cache_get_short_number(void)
{
    return MMI_CACHE_SHORT_NUMBER;
}
kal_uint16 mmi_rp_mmi_cache_get_double_number(void)
{
    return MMI_CACHE_DOUBLE_NUMBER;
}


const kal_uint16 MMI_CACHE_BYTE_ENUM_TABLE[MMI_CACHE_BYTE_NUMBER] =
{
    25974,   /* 0 -- NVRAM_BYTE_COVER_CLOSE_BACK_TO_IDLE */
    36507,   /* 1 -- NVRAM_WC_DST */
    26876,   /* 2 -- NVRAM_SETTING_LANG */
    25997,   /* 3 -- NVRAM_SETTING_PICTURE_QUALITY */
     9468,   /* 4 -- NVRAM_SMS_MISCELL_SETTING */
    25846,   /* 5 -- NVRAM_IME_ALPHABETIC_WORD_PREDICTION_FLAG */
     4811,   /* 6 -- NVRAM_MRE_SRV_DA_IS_WIFI_ONLY */
    31739,   /* 7 -- NVRAM_PHB_SAVE_CONTACT_NOTIFY */
    26030,   /* 8 -- NVRAM_NETSET_3G_CAPACITY_SIM */
    34129,   /* 9 -- NVRAM_IMGVIEW_VIEW_SYTLE */
    38867,   /* 10 -- NVRAM_PHNSET_LIVE_WALLPAPER */
    14373,   /* 11 -- NVRAM_PNS_SWITCH */
    27991,   /* 12 -- NVRAM_SETTING_AUTOKEYPADLOCK_TIME */
    36503,   /* 13 -- CURRENT_CITY */
    25845,   /* 14 -- NVRAM_IME_AUTO_COMPLETION_FLAG */
    25859,   /* 15 -- NVRAM_SETTING_HANDWRITING_ON */
    14271,   /* 16 -- NVRAM_EF_FMGR_SORT_OPTION_LID */
    38866,   /* 17 -- NVRAM_WALLPAPER_ROTATE_STATUS */
    31740,   /* 18 -- NVRAM_SSC_DISABLE_FLAG */
    11878,   /* 19 -- NVRAM_EM_INET_ACTIVE_ACCEPT_HEADER */
    31742,   /* 20 -- NVRAM_SETTING_SPEED_DIAL */
    40092,   /* 21 -- RESTORE_DEFAULT_OWNER_NO */
     9575,   /* 22 -- NVRAM_CALLSET_QUICK_END_FLAG */
    11879,   /* 23 -- NVRAM_EM_INET_ACTIVE_MMS_VERSION */
    25971,   /* 24 -- NVRAM_BYTE_LED_SETTING */
    34472,   /* 25 -- NVRAM_AUTO_VM_SETTING_VM_SUPPORT */
    31730,   /* 26 -- NVRAM_PHB_SPEAK_NAME_ON_OFF */
    25861,   /* 27 -- NVRAM_SETTING_STROKE_COLOR_INDEX */
    34773,   /* 28 -- NVRAM_AUDPLY_SINGLE_VOL */
     9574,   /* 29 -- NVRAM_CALLSET_REDIAL */
    31735,   /* 30 -- NVRAM_PHB_NAME_DISPLAY_TYPE */
    14374,   /* 31 -- NVRAM_PNS_CHANGE_SIM */
     9573,   /* 32 -- NVRAM_CALLSET_CALL_TIME_DISPLAY */
     9467,   /* 33 -- NVRAM_SMS_ACTIVE_PROFILE_INDEX */
    29902,   /* 34 -- NVRAM_SRV_SNDREC_QUALITY */
    11877,   /* 35 -- NVRAM_EM_INET_ACTIVE_USER_AGENT */
    36504,   /* 36 -- FOREIGN_CITY */
    26871,   /* 37 -- TIME_FORMAT */
    26873,   /* 38 -- RESTORE_DEFAULT_TIME_FORMAT */
    36505,   /* 39 -- NVRAM_SETTING_DT_DST */
    25975,   /* 40 -- NVRAM_BYTE_COVER_CLOSE_REJECT_CALL */
    25857,   /* 41 -- NVRAM_SETTING_PEN_SPEED */
    25860,   /* 42 -- NVRAM_SETTING_PEN_WIDTH */
    26029,   /* 43 -- NVRAM_NETSET_PREFERRED_MODE_PREV_RF_MODE */
    31741,   /* 44 -- NVRAM_IDLE_DIALER_SEARCH_SETTING */
    25967,   /* 45 -- NVRAM_SETTING_CONTRAST_SUBLCD_LEVEL */
    26872,   /* 46 -- DATE_FORMAT */
    26874,   /* 47 -- RESTORE_DEFAULT_DATE_FORMAT */
    31732,   /* 48 -- NVRAM_PHB_STARTUP_COPY_SIM2 */
    31733,   /* 49 -- NVRAM_PHB_STARTUP_COPY_SIM3 */
    31734,   /* 50 -- NVRAM_PHB_STARTUP_COPY_SIM4 */
    25851,   /* 51 -- NVRAM_IME_INPUT_PATTERN */
    31731,   /* 52 -- NVRAM_PHB_STARTUP_COPY_SIM */
     7765,   /* 53 -- NVRAM_PROFILES_LASTACTIVATED */
    25858,   /* 54 -- NVRAM_SETTING_LANGUAGE_FOLLOW_VK */
    25972,   /* 55 -- NVRAM_BYTE_BL_SETTING_LEVEL */
    40091,   /* 56 -- NVRAM_SETTING_OWNER_NO */
     9571,   /* 57 -- NVRAM_CALLSET_CTR_MODE */
    36509,   /* 58 -- NVRAM_DOWNLOAD_CITY1 */
    36510,   /* 59 -- NVRAM_DOWNLOAD_CITY2 */
    14372,   /* 60 -- NVRAM_PNS_INTERVAL */
    15111,   /* 61 -- NVRAM_DEFAULT_USB_APP */
    29827,   /* 62 -- NVRAM_EF_SENSOR_UI_ROTATION_SWITCH */
    25843,   /* 63 -- NVRAM_IME_SMART_MODE_CONFIG */
    26875,   /* 64 -- NVRAM_DT_SEP_FORMAT */
    25966,   /* 65 -- NVRAM_SETTING_CONTRAST_LEVEL */
    25849,   /* 66 -- NVRAM_IME_VIBRATION_FLAG */
    25847,   /* 67 -- NVRAM_IME_CHINESE_WORD_PREDICTION_FLAG */
    29901,   /* 68 -- NVRAM_SRV_SNDREC_STORAGE */
    26829,   /* 69 -- NVRAM_DUALMODE_MODE_SWITCH_TYPE */
    25850,   /* 70 -- NVRAM_IME_SOUND_FEEDBACK_FLAG */
    26028,   /* 71 -- NVRAM_NETSET_PREFERRED_MODE */
    25970,   /* 72 -- NVRAM_HDSET_MODE_VOICE_LEVEL */
    29903,   /* 73 -- NVRAM_AUTO_VM_SETTING_AUTO_VM */
    25969,   /* 74 -- NVRAM_LDSPK_MODE_VOICE_LEVEL */
    27990,   /* 75 -- NVRAM_SETTING_AUTOKEYPADLOCK */
    25968,   /* 76 -- NVRAM_NORMAL_MODE_VOICE_LEVEL */
    40093,   /* 77 -- NVRAM_SETTING_STATUS_DT_TIME */
     7764,   /* 78 -- NVRAM_PROFILES_ACTIVATED */
    25844,   /* 79 -- NVRAM_IME_AUTO_CAPITALIZATION_FLAG */
    25848,   /* 80 -- NVRAM_IME_AUTO_SPACE_FLAG */
    25976,   /* 81 -- NVRAM_BYTE_COVER_CLOSE_KEYPAD_LOCK */
    40094,   /* 82 -- NVRAM_AUTOUPDATE_DT_STATUS */
    28021,   /* 83 -- NVRAM_IDLE_DIALER_TTS_SETTING */
     9572,   /* 84 -- NVRAM_CALLSET_ANSWER_MODE */
};

const kal_uint16 MMI_CACHE_SHORT_ENUM_TABLE[MMI_CACHE_SHORT_NUMBER] =
{
     9470,   /* 0 -- NVRAM_SMSCOUNTERS_SENT_SHORT */
    25852,   /* 1 -- NVRAM_SETTING_PREFER_INPUT_METHOD */
     9469,   /* 2 -- NVRAM_SMS_CONCAT_MSG_REF_VALUE */
    39067,   /* 3 -- NVRAM_CURRENT_POWER_OFF_DISPLAY */
    25854,   /* 4 -- NVRAM_SETTING_WRITING_LANG */
    39066,   /* 5 -- NVRAM_CURRENT_POWER_ON_DISPLAY */
     9577,   /* 6 -- NVRAM_CALLSET_QUICK_END_TIME */
    31736,   /* 7 -- NVRAM_PHB_STORAGE_LOCATION */
     9471,   /* 8 -- NVRAM_SMSCOUNTERS_RECD_SHORT */
    36508,   /* 9 -- NVRAM_FRN_TIMEZONE */
    25853,   /* 10 -- RESTORE_PREFER_INPUT_METHOD */
    38871,   /* 11 -- RESTORE_DEFAULT_SETWALLPAPER_SUB */
    25973,   /* 12 -- NVRAM_BYTE_BL_SETTING_HFTIME */
    31738,   /* 13 -- NVRAM_PHB_VCARD_VERSION */
    25856,   /* 14 -- NVRAM_SETTING_ENABLED_WRITING_LANGUAGE */
    39065,   /* 15 -- NVRAM_RESTORE_POWER_OFF_DISPLAY */
    31737,   /* 16 -- NVRAM_PHB_NAME_LIST_FILTER */
    33031,   /* 17 -- NVRAM_POWER_ON_DISPLAY_SUCCESS */
     9576,   /* 18 -- NVRAM_CALLSET_CTR_TIME */
    38869,   /* 19 -- RESTORE_DEFAULT_FUNANDGAMES_SETWALLPAPER */
    36506,   /* 20 -- NVRAM_TIMEZONE */
    39064,   /* 21 -- NVRAM_RESTORE_POWER_ON_DISPLAY */
    25855,   /* 22 -- NVRAM_SETTING_WRITING_LANG_SUB */
    34130,   /* 23 -- NVRAM_IMGVIEW_STORAGE */
    38868,   /* 24 -- NVRAM_FUNANDGAMES_SETWALLPAPER */
    38870,   /* 25 -- NVRAM_SETWALLPAPER_SUB */
};

const kal_uint16 MMI_CACHE_DOUBLE_ENUM_TABLE[MMI_CACHE_DOUBLE_NUMBER] =
{
    11880,   /* 0 -- NVRAM_AUDIO_DEBUG_INFO1 */
    11881,   /* 1 -- NVRAM_AUDIO_DEBUG_INFO2 */
    11882,   /* 2 -- NVRAM_AUDIO_DEBUG_INFO3 */
    11883,   /* 3 -- NVRAM_AUDIO_DEBUG_INFO4 */
    38865,   /* 4 -- NVRAM_DISPCHAR_AVATAR_ONOFF_SERIALNUM */
    26840,   /* 5 -- NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE1 */
    26841,   /* 6 -- NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE2 */
    26842,   /* 7 -- NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE3 */
    26843,   /* 8 -- NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE4 */
    26844,   /* 9 -- NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE5 */
    26845,   /* 10 -- NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE6 */
    26846,   /* 11 -- NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE7 */
    26847,   /* 12 -- NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE8 */
    38863,   /* 13 -- NARAM_DISPCHAR_AVATAR_ONOFF */
     4803,   /* 14 -- NVRAM_MRE_SRV_DA_SIM1 */
     4805,   /* 15 -- NVRAM_MRE_SRV_DA_SIM2 */
     4807,   /* 16 -- NVRAM_MRE_SRV_DA_SIM3 */
     4809,   /* 17 -- NVRAM_MRE_SRV_DA_SIM4 */
    38862,   /* 18 -- NVRAM_DISPCHAR_AVATAR_WPSS */
     7766,   /* 19 -- NVRAM_SRV_PROF_EXT_MELODY_BITS */
    26848,   /* 20 -- NVRAM_PEN_CALIBRATION_VALUE1 */
    26849,   /* 21 -- NVRAM_PEN_CALIBRATION_VALUE2 */
    26850,   /* 22 -- NVRAM_PEN_CALIBRATION_VALUE3 */
    26851,   /* 23 -- NVRAM_PEN_CALIBRATION_VALUE4 */
    26852,   /* 24 -- NVRAM_PEN_CALIBRATION_VALUE5 */
    26853,   /* 25 -- NVRAM_PEN_CALIBRATION_VALUE6 */
    26854,   /* 26 -- NVRAM_PEN_CALIBRATION_VALUE7 */
    26855,   /* 27 -- NVRAM_PEN_CALIBRATION_VALUE8 */
    38864,   /* 28 -- NVRAM_DISPCHAR_AVATAR_WPSS_SERIALNUM */
     4804,   /* 29 -- NVRAM_MRE_SRV_DA_SIM1_PX */
     4806,   /* 30 -- NVRAM_MRE_SRV_DA_SIM2_PX */
     4808,   /* 31 -- NVRAM_MRE_SRV_DA_SIM3_PX */
     4810,   /* 32 -- NVRAM_MRE_SRV_DA_SIM4_PX */
};



const kal_uint32 NVRAM_EF_MMI_CACHE_BYTE_KEY_DEFAULT[NVRAM_MMI_CACHE_BYTE_KEY_SIZE * NVRAM_MMI_CACHE_BYTE_KEY_TOTAL / sizeof(kal_uint32)] =
{
    0x0033E086,   /* 0 -- NVRAM_BYTE_COVER_CLOSE_BACK_TO_IDLE */
    0x0588B0F2,   /* 1 -- NVRAM_WC_DST */
    0x0C5FC9DD,   /* 2 -- NVRAM_SETTING_LANG */
    0x1047E32F,   /* 3 -- NVRAM_SETTING_PICTURE_QUALITY */
    0x10FD69C4,   /* 4 -- NVRAM_SMS_MISCELL_SETTING */
    0x14915C3B,   /* 5 -- NVRAM_IME_ALPHABETIC_WORD_PREDICTION_FLAG */
    0x14F6111C,   /* 6 -- NVRAM_MRE_SRV_DA_IS_WIFI_ONLY */
    0x19F031B5,   /* 7 -- NVRAM_PHB_SAVE_CONTACT_NOTIFY */
    0x21246C43,   /* 8 -- NVRAM_NETSET_3G_CAPACITY_SIM */
    0x2322B5A4,   /* 9 -- NVRAM_IMGVIEW_VIEW_SYTLE */
    0x25031C82,   /* 10 -- NVRAM_PHNSET_LIVE_WALLPAPER */
    0x25F873DE,   /* 11 -- NVRAM_PNS_SWITCH */
    0x2A9FDCAF,   /* 12 -- NVRAM_SETTING_AUTOKEYPADLOCK_TIME */
    0x2E994CA8,   /* 13 -- CURRENT_CITY */
    0x338FF87D,   /* 14 -- NVRAM_IME_AUTO_COMPLETION_FLAG */
    0x33E27B20,   /* 15 -- NVRAM_SETTING_HANDWRITING_ON */
    0x33E2BC2F,   /* 16 -- NVRAM_EF_FMGR_SORT_OPTION_LID */
    0x3617F479,   /* 17 -- NVRAM_WALLPAPER_ROTATE_STATUS */
    0x3911329F,   /* 18 -- NVRAM_SSC_DISABLE_FLAG */
    0x3D3BB95F,   /* 19 -- NVRAM_EM_INET_ACTIVE_ACCEPT_HEADER */
    0x3F180537,   /* 20 -- NVRAM_SETTING_SPEED_DIAL */
    0x410A8A93,   /* 21 -- RESTORE_DEFAULT_OWNER_NO */
    0x4214065D,   /* 22 -- NVRAM_CALLSET_QUICK_END_FLAG */
    0x434B11A7,   /* 23 -- NVRAM_EM_INET_ACTIVE_MMS_VERSION */
    0x455E5A65,   /* 24 -- NVRAM_BYTE_LED_SETTING */
    0x495D7ACE,   /* 25 -- NVRAM_AUTO_VM_SETTING_VM_SUPPORT */
    0x4AC1FB21,   /* 26 -- NVRAM_PHB_SPEAK_NAME_ON_OFF */
    0x5A4072DE,   /* 27 -- NVRAM_SETTING_STROKE_COLOR_INDEX */
    0x5C355B2E,   /* 28 -- NVRAM_AUDPLY_SINGLE_VOL */
    0x5C5012DE,   /* 29 -- NVRAM_CALLSET_REDIAL */
    0x605F66F6,   /* 30 -- NVRAM_PHB_NAME_DISPLAY_TYPE */
    0x608C8352,   /* 31 -- NVRAM_PNS_CHANGE_SIM */
    0x613F6FD6,   /* 32 -- NVRAM_CALLSET_CALL_TIME_DISPLAY */
    0x61D48B89,   /* 33 -- NVRAM_SMS_ACTIVE_PROFILE_INDEX */
    0x62CC3DCF,   /* 34 -- NVRAM_SRV_SNDREC_QUALITY */
    0x63D39796,   /* 35 -- NVRAM_EM_INET_ACTIVE_USER_AGENT */
    0x63D46A2D,   /* 36 -- FOREIGN_CITY */
    0x655C92B2,   /* 37 -- TIME_FORMAT */
    0x66FB6043,   /* 38 -- RESTORE_DEFAULT_TIME_FORMAT */
    0x670179A5,   /* 39 -- NVRAM_SETTING_DT_DST */
    0x694DA578,   /* 40 -- NVRAM_BYTE_COVER_CLOSE_REJECT_CALL */
    0x6C769ED2,   /* 41 -- NVRAM_SETTING_PEN_SPEED */
    0x6CABCC51,   /* 42 -- NVRAM_SETTING_PEN_WIDTH */
    0x747C6326,   /* 43 -- NVRAM_NETSET_PREFERRED_MODE_PREV_RF_MODE */
    0x796DC810,   /* 44 -- NVRAM_IDLE_DIALER_SEARCH_SETTING */
    0x7E232E40,   /* 45 -- NVRAM_SETTING_CONTRAST_SUBLCD_LEVEL */
    0x82A4E6B1,   /* 46 -- DATE_FORMAT */
    0x8443B442,   /* 47 -- RESTORE_DEFAULT_DATE_FORMAT */
    0x8602068E,   /* 48 -- NVRAM_PHB_STARTUP_COPY_SIM2 */
    0x8602068F,   /* 49 -- NVRAM_PHB_STARTUP_COPY_SIM3 */
    0x86020690,   /* 50 -- NVRAM_PHB_STARTUP_COPY_SIM4 */
    0x88D6787D,   /* 51 -- NVRAM_IME_INPUT_PATTERN */
    0x90B5BE24,   /* 52 -- NVRAM_PHB_STARTUP_COPY_SIM */
    0x9F895786,   /* 53 -- NVRAM_PROFILES_LASTACTIVATED */
    0x9FC8B78B,   /* 54 -- NVRAM_SETTING_LANGUAGE_FOLLOW_VK */
    0xA08D6C77,   /* 55 -- NVRAM_BYTE_BL_SETTING_LEVEL */
    0xA4F4B75C,   /* 56 -- NVRAM_SETTING_OWNER_NO */
    0xA502111C,   /* 57 -- NVRAM_CALLSET_CTR_MODE */
    0xB084A4EF,   /* 58 -- NVRAM_DOWNLOAD_CITY1 */
    0xB084A4F0,   /* 59 -- NVRAM_DOWNLOAD_CITY2 */
    0xB0C01AEF,   /* 60 -- NVRAM_PNS_INTERVAL */
    0xB1A07148,   /* 61 -- NVRAM_DEFAULT_USB_APP */
    0xB3C62531,   /* 62 -- NVRAM_EF_SENSOR_UI_ROTATION_SWITCH */
    0xB4319F6A,   /* 63 -- NVRAM_IME_SMART_MODE_CONFIG */
    0xB4ADFEE7,   /* 64 -- NVRAM_DT_SEP_FORMAT */
    0xBA41A116,   /* 65 -- NVRAM_SETTING_CONTRAST_LEVEL */
    0xBAB0B4B7,   /* 66 -- NVRAM_IME_VIBRATION_FLAG */
    0xCA6F0937,   /* 67 -- NVRAM_IME_CHINESE_WORD_PREDICTION_FLAG */
    0xCBABBF4B,   /* 68 -- NVRAM_SRV_SNDREC_STORAGE */
    0xD4572DA9,   /* 69 -- NVRAM_DUALMODE_MODE_SWITCH_TYPE */
    0xD4BAD7B8,   /* 70 -- NVRAM_IME_SOUND_FEEDBACK_FLAG */
    0xD523D15B,   /* 71 -- NVRAM_NETSET_PREFERRED_MODE */
    0xD598E1F4,   /* 72 -- NVRAM_HDSET_MODE_VOICE_LEVEL */
    0xDC4F3C00,   /* 73 -- NVRAM_AUTO_VM_SETTING_AUTO_VM */
    0xDCE10CA4,   /* 74 -- NVRAM_LDSPK_MODE_VOICE_LEVEL */
    0xDE69511D,   /* 75 -- NVRAM_SETTING_AUTOKEYPADLOCK */
    0xDEED7E73,   /* 76 -- NVRAM_NORMAL_MODE_VOICE_LEVEL */
    0xE4CB8EFE,   /* 77 -- NVRAM_SETTING_STATUS_DT_TIME */
    0xE639E6DC,   /* 78 -- NVRAM_PROFILES_ACTIVATED */
    0xE928235D,   /* 79 -- NVRAM_IME_AUTO_CAPITALIZATION_FLAG */
    0xEE1A67D7,   /* 80 -- NVRAM_IME_AUTO_SPACE_FLAG */
    0xF8A67B30,   /* 81 -- NVRAM_BYTE_COVER_CLOSE_KEYPAD_LOCK */
    0xFA0E117A,   /* 82 -- NVRAM_AUTOUPDATE_DT_STATUS */
    0xFC2179AD,   /* 83 -- NVRAM_IDLE_DIALER_TTS_SETTING */
    0xFCAC03A9,   /* 84 -- NVRAM_CALLSET_ANSWER_MODE */
};

const kal_uint32 NVRAM_EF_MMI_CACHE_SHORT_KEY_DEFAULT[NVRAM_MMI_CACHE_SHORT_KEY_SIZE * NVRAM_MMI_CACHE_SHORT_KEY_TOTAL / sizeof(kal_uint32)] =
{
    0x07A09DA4,   /* 0 -- NVRAM_SMSCOUNTERS_SENT_SHORT */
    0x0C2C7116,   /* 1 -- NVRAM_SETTING_PREFER_INPUT_METHOD */
    0x1D98ABC2,   /* 2 -- NVRAM_SMS_CONCAT_MSG_REF_VALUE */
    0x238E70B2,   /* 3 -- NVRAM_CURRENT_POWER_OFF_DISPLAY */
    0x2D593480,   /* 4 -- NVRAM_SETTING_WRITING_LANG */
    0x3D11F342,   /* 5 -- NVRAM_CURRENT_POWER_ON_DISPLAY */
    0x421A59BE,   /* 6 -- NVRAM_CALLSET_QUICK_END_TIME */
    0x446216AE,   /* 7 -- NVRAM_PHB_STORAGE_LOCATION */
    0x4E468AE0,   /* 8 -- NVRAM_SMSCOUNTERS_RECD_SHORT */
    0x54329DD6,   /* 9 -- NVRAM_FRN_TIMEZONE */
    0x55C9E89D,   /* 10 -- RESTORE_PREFER_INPUT_METHOD */
    0x61E906E7,   /* 11 -- RESTORE_DEFAULT_SETWALLPAPER_SUB */
    0x6A59FE18,   /* 12 -- NVRAM_BYTE_BL_SETTING_HFTIME */
    0x79A7A46A,   /* 13 -- NVRAM_PHB_VCARD_VERSION */
    0x84CB0748,   /* 14 -- NVRAM_SETTING_ENABLED_WRITING_LANGUAGE */
    0x890C4A87,   /* 15 -- NVRAM_RESTORE_POWER_OFF_DISPLAY */
    0x910F4C1A,   /* 16 -- NVRAM_PHB_NAME_LIST_FILTER */
    0xA203F3C0,   /* 17 -- NVRAM_POWER_ON_DISPLAY_SUCCESS */
    0xA5052A46,   /* 18 -- NVRAM_CALLSET_CTR_TIME */
    0xA9842A5C,   /* 19 -- RESTORE_DEFAULT_FUNANDGAMES_SETWALLPAPER */
    0xAD3C1B39,   /* 20 -- NVRAM_TIMEZONE */
    0xBC370ACD,   /* 21 -- NVRAM_RESTORE_POWER_ON_DISPLAY */
    0xBCD765E1,   /* 22 -- NVRAM_SETTING_WRITING_LANG_SUB */
    0xBE99E6A4,   /* 23 -- NVRAM_IMGVIEW_STORAGE */
    0xDC2A15F6,   /* 24 -- NVRAM_FUNANDGAMES_SETWALLPAPER */
    0xEF592C81,   /* 25 -- NVRAM_SETWALLPAPER_SUB */
};

const kal_uint32 NVRAM_EF_MMI_CACHE_DOUBLE_KEY_DEFAULT[NVRAM_MMI_CACHE_DOUBLE_KEY_SIZE * NVRAM_MMI_CACHE_DOUBLE_KEY_TOTAL / sizeof(kal_uint32)] =
{
    0x029A6DEE,   /* 0 -- NVRAM_AUDIO_DEBUG_INFO1 */
    0x029A6DEF,   /* 1 -- NVRAM_AUDIO_DEBUG_INFO2 */
    0x029A6DF0,   /* 2 -- NVRAM_AUDIO_DEBUG_INFO3 */
    0x029A6DF1,   /* 3 -- NVRAM_AUDIO_DEBUG_INFO4 */
    0x29B4FC84,   /* 4 -- NVRAM_DISPCHAR_AVATAR_ONOFF_SERIALNUM */
    0x4C5F3D2A,   /* 5 -- NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE1 */
    0x4C5F3D2B,   /* 6 -- NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE2 */
    0x4C5F3D2C,   /* 7 -- NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE3 */
    0x4C5F3D2D,   /* 8 -- NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE4 */
    0x4C5F3D2E,   /* 9 -- NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE5 */
    0x4C5F3D2F,   /* 10 -- NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE6 */
    0x4C5F3D30,   /* 11 -- NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE7 */
    0x4C5F3D31,   /* 12 -- NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE8 */
    0x55D698C6,   /* 13 -- NARAM_DISPCHAR_AVATAR_ONOFF */
    0x62F30CB5,   /* 14 -- NVRAM_MRE_SRV_DA_SIM1 */
    0x62F30CB6,   /* 15 -- NVRAM_MRE_SRV_DA_SIM2 */
    0x62F30CB7,   /* 16 -- NVRAM_MRE_SRV_DA_SIM3 */
    0x62F30CB8,   /* 17 -- NVRAM_MRE_SRV_DA_SIM4 */
    0x98AE5398,   /* 18 -- NVRAM_DISPCHAR_AVATAR_WPSS */
    0xB68B1B79,   /* 19 -- NVRAM_SRV_PROF_EXT_MELODY_BITS */
    0xC384715B,   /* 20 -- NVRAM_PEN_CALIBRATION_VALUE1 */
    0xC384715C,   /* 21 -- NVRAM_PEN_CALIBRATION_VALUE2 */
    0xC384715D,   /* 22 -- NVRAM_PEN_CALIBRATION_VALUE3 */
    0xC384715E,   /* 23 -- NVRAM_PEN_CALIBRATION_VALUE4 */
    0xC384715F,   /* 24 -- NVRAM_PEN_CALIBRATION_VALUE5 */
    0xC3847160,   /* 25 -- NVRAM_PEN_CALIBRATION_VALUE6 */
    0xC3847161,   /* 26 -- NVRAM_PEN_CALIBRATION_VALUE7 */
    0xC3847162,   /* 27 -- NVRAM_PEN_CALIBRATION_VALUE8 */
    0xD017390B,   /* 28 -- NVRAM_DISPCHAR_AVATAR_WPSS_SERIALNUM */
    0xD9F529D2,   /* 29 -- NVRAM_MRE_SRV_DA_SIM1_PX */
    0xD9F59E31,   /* 30 -- NVRAM_MRE_SRV_DA_SIM2_PX */
    0xD9F61290,   /* 31 -- NVRAM_MRE_SRV_DA_SIM3_PX */
    0xD9F686EF,   /* 32 -- NVRAM_MRE_SRV_DA_SIM4_PX */
};



#ifdef __MTK_INTERNAL__
/* type (1: byte cache,  2: short cache   8:double cache) */
/* This API is only used for meta tool */
kal_int16 mmi_rp_mmi_cache_search_index(kal_uint16 nDataItemId, kal_uint8 nDataType)
{
    kal_uint16 index, total= 0;
    const kal_uint16 *tbl;

    switch(nDataType)
    {
    case 1:
        tbl = MMI_CACHE_BYTE_ENUM_TABLE;
        total = MMI_CACHE_BYTE_NUMBER;
        break;
    case 2:
        tbl = MMI_CACHE_SHORT_ENUM_TABLE;
        total = MMI_CACHE_SHORT_NUMBER;
        break;
    case 8:
        tbl = MMI_CACHE_DOUBLE_ENUM_TABLE;
        total = MMI_CACHE_DOUBLE_NUMBER;
        break;
    default:
        tbl = NULL;
        total = 0;
    }
    for( index = 0 ; index < total ; index++)
    {
        if (tbl[index] == nDataItemId)
            return index;
    }
    return -1;
}
#endif


/********************************************************
 *  This file is generated automatically by resource gen
 *  Please do not modify it here manually 
 ***********************************************************/



#include "mmi_res_range_def.h"
#include "nvram_enums.h"
#include "nvram_interface.h"



/*****************************************************************************
 * FUNCTION
 *  nvram_restore_byte_cache()
 * DESCRIPTION
 *  used to restore mmi_cache_byte to default value
 * PARAMETERS
 *  buffer    [IN]
 * RETURNS
 *  none
 *****************************************************************************/
void nvram_restore_byte_cache(nvram_reset_category_enum category,nvram_app_id_enum app_id, kal_uint8 *buffer)
{
    /*----------------------------------------------------------------*/
    /* Local Variables                                                */
    /*----------------------------------------------------------------*/

    /*----------------------------------------------------------------*/
    /* Code Body                                                      */
    /*----------------------------------------------------------------*/
    kal_uint8 *def_buf;
    nvram_get_default_value(NVRAM_EF_CACHE_BYTE_LID, 1, &def_buf);
    switch(app_id)
    {
    case 0:  /* for restore factory, reset all app item */
    case APP_MRE: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_BOOTUP: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_IMAGEVIEWER: 
        buffer[  9] = def_buf[  9];     /* 34129: NVRAM_IMGVIEW_VIEW_SYTLE */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_SOUNDRECORDER: 
        buffer[ 25] = def_buf[ 25];     /* 34472: NVRAM_AUTO_VM_SETTING_VM_SUPPORT */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_AUDIOPLAYER: 
        buffer[ 28] = def_buf[ 28];     /* 34773: NVRAM_AUDPLY_SINGLE_VOL */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_WORLDCLOCK: 
        buffer[ 13] = def_buf[ 13];     /* 36503: CURRENT_CITY */
        buffer[ 36] = def_buf[ 36];     /* 36504: FOREIGN_CITY */
        buffer[ 39] = def_buf[ 39];     /* 36505: NVRAM_SETTING_DT_DST */
        buffer[  1] = def_buf[  1];     /* 36507: NVRAM_WC_DST */
        buffer[ 58] = def_buf[ 58];     /* 36509: NVRAM_DOWNLOAD_CITY1 */
        buffer[ 59] = def_buf[ 59];     /* 36510: NVRAM_DOWNLOAD_CITY2 */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_WALLPAPER: 
        buffer[ 17] = def_buf[ 17];     /* 38866: NVRAM_WALLPAPER_ROTATE_STATUS */
        buffer[ 10] = def_buf[ 10];     /* 38867: NVRAM_PHNSET_LIVE_WALLPAPER */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_PHNSET_ONOFF: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_PHONESETTING_NEW: 
        buffer[ 56] = def_buf[ 21];     /* 40091: NVRAM_SETTING_OWNER_NO = 40092: RESTORE_DEFAULT_OWNER_NO*/
        buffer[ 77] = def_buf[ 77];     /* 40093: NVRAM_SETTING_STATUS_DT_TIME */
        buffer[ 82] = def_buf[ 82];     /* 40094: NVRAM_AUTOUPDATE_DT_STATUS */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_PROF: 
        buffer[ 78] = def_buf[ 78];     /*  7764: NVRAM_PROFILES_ACTIVATED */
        buffer[ 53] = def_buf[ 53];     /*  7765: NVRAM_PROFILES_LASTACTIVATED */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_SMS: 
        buffer[  4] = def_buf[  4];     /*  9468: NVRAM_SMS_MISCELL_SETTING */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_EDITOR: 
        buffer[ 63] = def_buf[ 63];     /* 25843: NVRAM_IME_SMART_MODE_CONFIG */
        buffer[ 79] = def_buf[ 79];     /* 25844: NVRAM_IME_AUTO_CAPITALIZATION_FLAG */
        buffer[ 14] = def_buf[ 14];     /* 25845: NVRAM_IME_AUTO_COMPLETION_FLAG */
        buffer[  5] = def_buf[  5];     /* 25846: NVRAM_IME_ALPHABETIC_WORD_PREDICTION_FLAG */
        buffer[ 67] = def_buf[ 67];     /* 25847: NVRAM_IME_CHINESE_WORD_PREDICTION_FLAG */
        buffer[ 80] = def_buf[ 80];     /* 25848: NVRAM_IME_AUTO_SPACE_FLAG */
        buffer[ 66] = def_buf[ 66];     /* 25849: NVRAM_IME_VIBRATION_FLAG */
        buffer[ 70] = def_buf[ 70];     /* 25850: NVRAM_IME_SOUND_FEEDBACK_FLAG */
        buffer[ 51] = def_buf[ 51];     /* 25851: NVRAM_IME_INPUT_PATTERN */
        buffer[ 41] = def_buf[ 41];     /* 25857: NVRAM_SETTING_PEN_SPEED */
        buffer[ 54] = def_buf[ 54];     /* 25858: NVRAM_SETTING_LANGUAGE_FOLLOW_VK */
        buffer[ 15] = def_buf[ 15];     /* 25859: NVRAM_SETTING_HANDWRITING_ON */
        buffer[ 42] = def_buf[ 42];     /* 25860: NVRAM_SETTING_PEN_WIDTH */
        buffer[ 27] = def_buf[ 27];     /* 25861: NVRAM_SETTING_STROKE_COLOR_INDEX */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_ENGINEERMODE1: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_FILEMANAGER: 
        buffer[ 16] = def_buf[ 16];     /* 14271: NVRAM_EF_FMGR_SORT_OPTION_LID */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_PNS: 
        buffer[ 60] = def_buf[ 60];     /* 14372: NVRAM_PNS_INTERVAL */
        buffer[ 11] = def_buf[ 11];     /* 14373: NVRAM_PNS_SWITCH */
        buffer[ 31] = def_buf[ 31];     /* 14374: NVRAM_PNS_CHANGE_SIM */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_USBSRV: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_GPIO: 
        buffer[ 65] = def_buf[ 65];     /* 25966: NVRAM_SETTING_CONTRAST_LEVEL */
        buffer[ 24] = def_buf[ 24];     /* 25971: NVRAM_BYTE_LED_SETTING */
        buffer[ 55] = def_buf[ 55];     /* 25972: NVRAM_BYTE_BL_SETTING_LEVEL */
        buffer[  0] = def_buf[  0];     /* 25974: NVRAM_BYTE_COVER_CLOSE_BACK_TO_IDLE */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_GPIO: 
        buffer[  3] = def_buf[  3];     /* 25997: NVRAM_SETTING_PICTURE_QUALITY */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_NETSET: 
        buffer[ 71] = def_buf[ 71];     /* 26028: NVRAM_NETSET_PREFERRED_MODE */
        buffer[ 43] = def_buf[ 43];     /* 26029: NVRAM_NETSET_PREFERRED_MODE_PREV_RF_MODE */
        buffer[  8] = def_buf[  8];     /* 26030: NVRAM_NETSET_3G_CAPACITY_SIM */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_CALLSET: 
        buffer[ 57] = def_buf[ 57];     /*  9571: NVRAM_CALLSET_CTR_MODE */
        buffer[ 84] = def_buf[ 84];     /*  9572: NVRAM_CALLSET_ANSWER_MODE */
        buffer[ 32] = def_buf[ 32];     /*  9573: NVRAM_CALLSET_CALL_TIME_DISPLAY */
        buffer[ 29] = def_buf[ 29];     /*  9574: NVRAM_CALLSET_REDIAL */
        buffer[ 22] = def_buf[ 22];     /*  9575: NVRAM_CALLSET_QUICK_END_FLAG */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_MODESWITCH: 
        buffer[ 69] = def_buf[ 69];     /* 26829: NVRAM_DUALMODE_MODE_SWITCH_TYPE */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_PEN_CALIBRATION: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_GENERAL_SETTING: 
        buffer[ 37] = def_buf[ 37];     /* 26871: TIME_FORMAT */
        buffer[ 46] = def_buf[ 46];     /* 26872: DATE_FORMAT */
        buffer[ 64] = def_buf[ 64];     /* 26875: NVRAM_DT_SEP_FORMAT */
        buffer[  2] = def_buf[  2];     /* 26876: NVRAM_SETTING_LANG */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case CUI_DIALER: 
        buffer[ 83] = def_buf[ 83];     /* 28021: NVRAM_IDLE_DIALER_TTS_SETTING */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_SCR_LOCKER: 
        buffer[ 75] = def_buf[ 75];     /* 27990: NVRAM_SETTING_AUTOKEYPADLOCK */
        buffer[ 12] = def_buf[ 12];     /* 27991: NVRAM_SETTING_AUTOKEYPADLOCK_TIME */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_AUTO_ROTATE: 
        buffer[ 62] = def_buf[ 62];     /* 29827: NVRAM_EF_SENSOR_UI_ROTATION_SWITCH */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_SOUNDREC: 
        buffer[ 68] = def_buf[ 68];     /* 29901: NVRAM_SRV_SNDREC_STORAGE */
        buffer[ 34] = def_buf[ 34];     /* 29902: NVRAM_SRV_SNDREC_QUALITY */
        buffer[ 73] = def_buf[ 73];     /* 29903: NVRAM_AUTO_VM_SETTING_AUTO_VM */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_PHB: 
        buffer[ 26] = def_buf[ 26];     /* 31730: NVRAM_PHB_SPEAK_NAME_ON_OFF */
        buffer[ 30] = def_buf[ 30];     /* 31735: NVRAM_PHB_NAME_DISPLAY_TYPE */
        buffer[  7] = def_buf[  7];     /* 31739: NVRAM_PHB_SAVE_CONTACT_NOTIFY */
        buffer[ 44] = def_buf[ 44];     /* 31741: NVRAM_IDLE_DIALER_SEARCH_SETTING */
        buffer[ 20] = def_buf[ 20];     /* 31742: NVRAM_SETTING_SPEED_DIAL */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    default:
        break;
    };
}



/*****************************************************************************
 * FUNCTION
 *  nvram_restore_short_cache()
 * DESCRIPTION
 *  used to restore mmi_cache_short to default value
 * PARAMETERS
 *  buffer    [IN]
 * RETURNS
 *  none
 *****************************************************************************/
void nvram_restore_short_cache(nvram_reset_category_enum category,nvram_app_id_enum app_id, kal_uint8 *buffer)
{
    /*----------------------------------------------------------------*/
    /* Local Variables                                                */
    /*----------------------------------------------------------------*/

    /*----------------------------------------------------------------*/
    /* Code Body                                                      */
    /*----------------------------------------------------------------*/
    kal_uint8 *def_buf;
    nvram_get_default_value(NVRAM_EF_CACHE_SHORT_LID, 1, &def_buf);
    switch(app_id)
    {
    case 0:  /* for restore factory, reset all app item */
    case APP_MRE: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_BOOTUP: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_IMAGEVIEWER: 
        buffer[ 46] = def_buf[ 46];     /* 34130: NVRAM_IMGVIEW_STORAGE */
        buffer[ 47] = def_buf[ 47];
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_SOUNDRECORDER: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_AUDIOPLAYER: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_WORLDCLOCK: 
        buffer[ 40] = def_buf[ 40];     /* 36506: NVRAM_TIMEZONE */
        buffer[ 41] = def_buf[ 41];
        buffer[ 18] = def_buf[ 18];     /* 36508: NVRAM_FRN_TIMEZONE */
        buffer[ 19] = def_buf[ 19];
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_WALLPAPER: 
        buffer[ 48] = def_buf[ 48];     /* 38868: NVRAM_FUNANDGAMES_SETWALLPAPER */
        buffer[ 49] = def_buf[ 49];
        buffer[ 50] = def_buf[ 22];     /* 38870: NVRAM_SETWALLPAPER_SUB = 38871: RESTORE_DEFAULT_SETWALLPAPER_SUB*/
        buffer[ 51] = def_buf[ 23];
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_PHNSET_ONOFF: 
        buffer[ 10] = def_buf[ 42];     /* 39066: NVRAM_CURRENT_POWER_ON_DISPLAY = 39064: NVRAM_RESTORE_POWER_ON_DISPLAY*/
        buffer[ 11] = def_buf[ 43];
        buffer[  6] = def_buf[ 30];     /* 39067: NVRAM_CURRENT_POWER_OFF_DISPLAY = 39065: NVRAM_RESTORE_POWER_OFF_DISPLAY*/
        buffer[  7] = def_buf[ 31];
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_PHONESETTING_NEW: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_PROF: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_SMS: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_EDITOR: 
        buffer[  2] = def_buf[ 20];     /* 25852: NVRAM_SETTING_PREFER_INPUT_METHOD = 25853: RESTORE_PREFER_INPUT_METHOD*/
        buffer[  3] = def_buf[ 21];
        buffer[  8] = def_buf[  8];     /* 25854: NVRAM_SETTING_WRITING_LANG */
        buffer[  9] = def_buf[  9];
        buffer[ 44] = def_buf[ 44];     /* 25855: NVRAM_SETTING_WRITING_LANG_SUB */
        buffer[ 45] = def_buf[ 45];
        buffer[ 28] = def_buf[ 28];     /* 25856: NVRAM_SETTING_ENABLED_WRITING_LANGUAGE */
        buffer[ 29] = def_buf[ 29];
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_ENGINEERMODE1: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_FILEMANAGER: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_PNS: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_USBSRV: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_GPIO: 
        buffer[ 24] = def_buf[ 24];     /* 25973: NVRAM_BYTE_BL_SETTING_HFTIME */
        buffer[ 25] = def_buf[ 25];
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_GPIO: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_NETSET: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_CALLSET: 
        buffer[ 12] = def_buf[ 12];     /*  9577: NVRAM_CALLSET_QUICK_END_TIME */
        buffer[ 13] = def_buf[ 13];
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_MODESWITCH: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_PEN_CALIBRATION: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_GENERAL_SETTING: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case CUI_DIALER: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_SCR_LOCKER: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_AUTO_ROTATE: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_SOUNDREC: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_PHB: 
        buffer[ 14] = def_buf[ 14];     /* 31736: NVRAM_PHB_STORAGE_LOCATION */
        buffer[ 15] = def_buf[ 15];
        buffer[ 32] = def_buf[ 32];     /* 31737: NVRAM_PHB_NAME_LIST_FILTER */
        buffer[ 33] = def_buf[ 33];
        buffer[ 26] = def_buf[ 26];     /* 31738: NVRAM_PHB_VCARD_VERSION */
        buffer[ 27] = def_buf[ 27];
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    default:
        break;
    };
}



/*****************************************************************************
 * FUNCTION
 *  nvram_restore_double_cache()
 * DESCRIPTION
 *  used to restore mmi_cache_double to default value
 * PARAMETERS
 *  buffer    [IN]
 * RETURNS
 *  none
 *****************************************************************************/
void nvram_restore_double_cache(nvram_reset_category_enum category,nvram_app_id_enum app_id, kal_uint8 *buffer)
{
    /*----------------------------------------------------------------*/
    /* Local Variables                                                */
    /*----------------------------------------------------------------*/

    /*----------------------------------------------------------------*/
    /* Code Body                                                      */
    /*----------------------------------------------------------------*/
    kal_uint8 *def_buf;
    nvram_get_default_value(NVRAM_EF_CACHE_DOUBLE_LID, 1, &def_buf);
    switch(app_id)
    {
    case 0:  /* for restore factory, reset all app item */
    case APP_MRE: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_BOOTUP: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_IMAGEVIEWER: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_SOUNDRECORDER: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_AUDIOPLAYER: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_WORLDCLOCK: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_WALLPAPER: 
        buffer[144] = def_buf[144];     /* 38862: NVRAM_DISPCHAR_AVATAR_WPSS */
        buffer[145] = def_buf[145];
        buffer[146] = def_buf[146];
        buffer[147] = def_buf[147];
        buffer[148] = def_buf[148];
        buffer[149] = def_buf[149];
        buffer[150] = def_buf[150];
        buffer[151] = def_buf[151];
        buffer[104] = def_buf[104];     /* 38863: NARAM_DISPCHAR_AVATAR_ONOFF */
        buffer[105] = def_buf[105];
        buffer[106] = def_buf[106];
        buffer[107] = def_buf[107];
        buffer[108] = def_buf[108];
        buffer[109] = def_buf[109];
        buffer[110] = def_buf[110];
        buffer[111] = def_buf[111];
        buffer[224] = def_buf[224];     /* 38864: NVRAM_DISPCHAR_AVATAR_WPSS_SERIALNUM */
        buffer[225] = def_buf[225];
        buffer[226] = def_buf[226];
        buffer[227] = def_buf[227];
        buffer[228] = def_buf[228];
        buffer[229] = def_buf[229];
        buffer[230] = def_buf[230];
        buffer[231] = def_buf[231];
        buffer[ 32] = def_buf[ 32];     /* 38865: NVRAM_DISPCHAR_AVATAR_ONOFF_SERIALNUM */
        buffer[ 33] = def_buf[ 33];
        buffer[ 34] = def_buf[ 34];
        buffer[ 35] = def_buf[ 35];
        buffer[ 36] = def_buf[ 36];
        buffer[ 37] = def_buf[ 37];
        buffer[ 38] = def_buf[ 38];
        buffer[ 39] = def_buf[ 39];
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_PHNSET_ONOFF: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_PHONESETTING_NEW: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_PROF: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_SMS: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_EDITOR: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_ENGINEERMODE1: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_FILEMANAGER: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_PNS: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_USBSRV: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_GPIO: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_GPIO: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_NETSET: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_CALLSET: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_MODESWITCH: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_PEN_CALIBRATION: 
        buffer[160] = def_buf[ 40];     /* 26848: NVRAM_PEN_CALIBRATION_VALUE1 = 26840: NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE1*/
        buffer[161] = def_buf[ 41];
        buffer[162] = def_buf[ 42];
        buffer[163] = def_buf[ 43];
        buffer[164] = def_buf[ 44];
        buffer[165] = def_buf[ 45];
        buffer[166] = def_buf[ 46];
        buffer[167] = def_buf[ 47];
        buffer[168] = def_buf[ 48];     /* 26849: NVRAM_PEN_CALIBRATION_VALUE2 = 26841: NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE2*/
        buffer[169] = def_buf[ 49];
        buffer[170] = def_buf[ 50];
        buffer[171] = def_buf[ 51];
        buffer[172] = def_buf[ 52];
        buffer[173] = def_buf[ 53];
        buffer[174] = def_buf[ 54];
        buffer[175] = def_buf[ 55];
        buffer[176] = def_buf[ 56];     /* 26850: NVRAM_PEN_CALIBRATION_VALUE3 = 26842: NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE3*/
        buffer[177] = def_buf[ 57];
        buffer[178] = def_buf[ 58];
        buffer[179] = def_buf[ 59];
        buffer[180] = def_buf[ 60];
        buffer[181] = def_buf[ 61];
        buffer[182] = def_buf[ 62];
        buffer[183] = def_buf[ 63];
        buffer[184] = def_buf[ 64];     /* 26851: NVRAM_PEN_CALIBRATION_VALUE4 = 26843: NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE4*/
        buffer[185] = def_buf[ 65];
        buffer[186] = def_buf[ 66];
        buffer[187] = def_buf[ 67];
        buffer[188] = def_buf[ 68];
        buffer[189] = def_buf[ 69];
        buffer[190] = def_buf[ 70];
        buffer[191] = def_buf[ 71];
        buffer[192] = def_buf[ 72];     /* 26852: NVRAM_PEN_CALIBRATION_VALUE5 = 26844: NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE5*/
        buffer[193] = def_buf[ 73];
        buffer[194] = def_buf[ 74];
        buffer[195] = def_buf[ 75];
        buffer[196] = def_buf[ 76];
        buffer[197] = def_buf[ 77];
        buffer[198] = def_buf[ 78];
        buffer[199] = def_buf[ 79];
        buffer[200] = def_buf[ 80];     /* 26853: NVRAM_PEN_CALIBRATION_VALUE6 = 26845: NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE6*/
        buffer[201] = def_buf[ 81];
        buffer[202] = def_buf[ 82];
        buffer[203] = def_buf[ 83];
        buffer[204] = def_buf[ 84];
        buffer[205] = def_buf[ 85];
        buffer[206] = def_buf[ 86];
        buffer[207] = def_buf[ 87];
        buffer[208] = def_buf[ 88];     /* 26854: NVRAM_PEN_CALIBRATION_VALUE7 = 26846: NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE7*/
        buffer[209] = def_buf[ 89];
        buffer[210] = def_buf[ 90];
        buffer[211] = def_buf[ 91];
        buffer[212] = def_buf[ 92];
        buffer[213] = def_buf[ 93];
        buffer[214] = def_buf[ 94];
        buffer[215] = def_buf[ 95];
        buffer[216] = def_buf[ 96];     /* 26855: NVRAM_PEN_CALIBRATION_VALUE8 = 26847: NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE8*/
        buffer[217] = def_buf[ 97];
        buffer[218] = def_buf[ 98];
        buffer[219] = def_buf[ 99];
        buffer[220] = def_buf[100];
        buffer[221] = def_buf[101];
        buffer[222] = def_buf[102];
        buffer[223] = def_buf[103];
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_GENERAL_SETTING: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case CUI_DIALER: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_SCR_LOCKER: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_AUTO_ROTATE: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_SOUNDREC: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_PHB: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    default:
        break;
    };
}


